---
- name: change when test
  hosts: db
  tasks:
    - name: run cal command 
      shell: /usr/bin/cal 
      register: cal_result 
      changed_when: false

    - name: print cal_result value
      debug:
        var: cal_result

