---
- name: changed_when example 2
  hosts: db
  tasks:
    - name: run date command 
      command: /usr/bin/date
      register: date_result

    - name: print date_result value
      debug:
        msg: yes...today is Sat Jun 15   
      changed_when: '"JUN 15" in date_result.stdout'  
