---
- name: install IP-SAN
  hosts: db
  tasks:
    - name: install iscsi pkg
      dnf:
        name: iscsi-initiator-utils
        state: latest

    - name: run iscsi command
      command: iscsiadm -m session    
      register: bbb
#      ignore_errors: true
      failed_when: bbb.rc not in (0, 21, 77, 22)

    - name: print bbb value 
      debug:
        var: bbb     