---
- name: force handler test
  hosts: db
  force_handlers: true
  tasks:
    - name: install chrony pkg 
      dnf:
        name: chrony
        state: present

    - name: call handler
      shell: /usr/bin/date
      notify:
        - restart_chronyd

    - name: install pkg
      dnf:
        name: tre
        state: latest

    - name: print dummy message
      debug:
        msg: good bye 
  
  handlers:
    - name: restart_chronyd
      service :
        name: chronyd 
        state: restarted

