---
- name: loop and when
  hosts: db 
  tasks:
    - name: install big pkg
      dnf: 
        name: mariadb-server
        state: latest
      loop: "{{ ansible_facts.mounts }}"  
      when:  
        - item.mount == "/"
        - item.size_available >= 1000000000